version: 0.2

phases:

  install:
    commands:
      - gem update

  build:
    commands:
      - unset BUNDLER_VERSION
      - env
      - bundle --version
      - bundle install
      - jekyll build

