version: 0.2

env:
  variables:
    BUNDLER_VERSION: 2.0.1

phases:

  install:
    commands:
      - gem update

  build:
    commands:
      - env
      - bundle --version
      - bundle install
      - jekyll build

