version: 0.2

phases:

  install:
    commands:
      - gem uninstall bundler
      - which bundle
      - bundle --version
      - gem install bundler
      - bundle --version
      - bundle install

  build:
    commands:
      - jekyll build

